spring.application.name=auth-demo

# Postgres database
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT configuration
# secret should be stored in .env file but for sake of demonstration, it is stored here
jwt.secret=DGV1SBtDgtdBcLV1tLAg7Rd/Us1DXl+FAKDGoy/Ic3Y=
# Access token is set to expire in 15 minutes
jwt.access-token-expiration=900000
# Refresh token is set to expire in 7 days
jwt.refresh-token-expiration=604800000

# Redis caching (UserCacheService)
spring.cache.type=redis
